name: modberg
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - altair=4.2.0
  - appnope=0.1.3
  - arrow-cpp=6.0.1
  - asttokens=2.0.8
  - attrs=22.1.0
  - aws-c-auth=0.6.8
  - aws-c-cal=0.5.12
  - aws-c-common=0.6.17
  - aws-c-compression=0.2.14
  - aws-c-event-stream=0.2.7
  - aws-c-http=0.6.10
  - aws-c-io=0.10.14
  - aws-c-mqtt=0.7.10
  - aws-c-s3=0.1.29
  - aws-c-sdkutils=0.1.1
  - aws-checksums=0.1.12
  - aws-crt-cpp=0.17.10
  - aws-sdk-cpp=1.9.160
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cachetools=5.2.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - commonmark=0.9.1
  - cryptography=38.0.2
  - dataclasses=0.8
  - debugpy=1.6.3
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.1.1
  - freetype=2.12.1
  - future=0.18.2
  - gflags=2.2.2
  - gitdb=4.0.9
  - gitpython=3.1.29
  - glog=0.5.0
  - grpc-cpp=1.42.0
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - ipykernel=6.16.2
  - ipython=8.5.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.4
  - jupyter_core=4.11.1
  - jupyterlab_widgets=3.0.3
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.4.0
  - libutf8proc=2.7.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - numpy=1.23.4
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - orc=1.7.1
  - packaging=21.3
  - pandas=1.5.1
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3
  - pkgutil-resolve-name=1.3.10
  - prompt-toolkit=3.0.31
  - protobuf=3.19.4
  - psutil=5.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=6.0.1
  - pycparser=2.21
  - pydeck=0.8.0b4
  - pygments=2.13.0
  - pympler=1.0.1
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-tzdata=2022.5
  - python_abi=3.10
  - pytz=2022.5
  - pytz-deprecation-shim=0.1.0.post0
  - pyyaml=6.0
  - pyzmq=24.0.1
  - re2=2021.11.01
  - readline=8.1.2
  - requests=2.28.1
  - rich=12.6.0
  - semver=2.13.0
  - setuptools=65.5.0
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.9
  - stack_data=0.5.1
  - streamlit=1.14.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.5.0
  - typing_extensions=4.4.0
  - tzdata=2022e
  - tzlocal=4.2
  - urllib3=1.26.11
  - validators=0.18.2
  - watchdog=2.1.9
  - wcwidth=0.2.5
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
