name: frost-depth
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cryptography=38.0.4
  - idna=3.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - ncurses=6.3
  - numpy=1.23.5
  - openssl=3.0.7
  - pandas=1.5.2
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.1.0
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.6
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=65.5.1
  - six=1.16.0
  - tk=8.6.12
  - urllib3=1.26.13
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - altair==4.2.0
    - attrs==22.1.0
    - blinker==1.5
    - cachetools==5.2.0
    - click==8.1.3
    - commonmark==0.9.1
    - decorator==5.1.1
    - entrypoints==0.4
    - gitdb==4.0.10
    - gitpython==3.1.29
    - importlib-metadata==5.1.0
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - markupsafe==2.1.1
    - packaging==22.0
    - pillow==9.3.0
    - protobuf==3.20.3
    - pyarrow==10.0.1
    - pydeck==0.8.0
    - pygments==2.13.0
    - pympler==1.0.1
    - pyrsistent==0.19.2
    - pytz-deprecation-shim==0.1.0.post0
    - rich==12.6.0
    - semver==2.13.0
    - smmap==5.0.0
    - streamlit==1.15.2
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.2
    - typing-extensions==4.4.0
    - tzdata==2022.7
    - tzlocal==4.2
    - validators==0.20.0
    - zipp==3.11.0
