[theme]

# Primary accent color for interactive elements.
primaryColor = "#4b8cc5"

# Background color for the main content area.
backgroundColor = "#f7f6eb"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f7f6eb"

# Color used for almost all text.
textColor = "#4e5354"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "monospace"
